services:
  postgres:
    image: postgres:18
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
      image: redis:8.8
      container_name: my-redis
      restart: always
      ports:
        - '6379:6379'
      volumes:
        - redis-data:/data
      command: --requirepass ${REDIS_PASSWORD}

volumes:
  postgres_data:
  redis-data: